version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME:-0}
        GROUP_NAME: ${GROUP_NAME:-0}
    container_name: smart_campus_php
    volumes:
      - "./:/var/www/html/:cached"
      - symfony-var:/var/www/html/projet_symfony/var
      - symfony-vendor:/var/www/html/projet_symfony/vendor
  web:
    container_name: smart_campus_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8888:80"
      - "8887:81"
    volumes:
      - "./:/var/www/html/:cached"
      - symfony-var:/var/www/html/projet_symfony/var
      - symfony-vendor:/var/www/html/projet_symfony/vendor
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: smart_campus_pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8886:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: smart_campus_db
    ports:
      - "3307:3306" # mysql
    environment:
      MYSQL_DATABASE: smart_campus
      MYSQL_USER: smart_campus_user
      MYSQL_PASSWORD: smart_campus_password
      MYSQL_ROOT_PASSWORD: smart_campus_root_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  symfony-var:
  symfony-vendor:
  db-data:

